name: 'mern-demo'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=mern-demo
      - MONGO_INITDB_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_PASSWORD}

volumes:
  mongodb_data: